2021-05-06 19:10:48,828 - ERROR - telegram.ext.updater - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2021-05-06 19:10:48,833 - ERROR - root - urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) - Class: TelegramBot - None
2021-05-06 19:11:56,988 - ERROR - telegram.ext.updater - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2021-05-06 19:11:56,988 - ERROR - root - urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) - Class: TelegramBot - None
2021-05-06 19:12:07,998 - WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x11388f190>, 'Connection to api.telegram.org timed out. (connect timeout=10)')': /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates
2021-05-06 19:12:45,703 - ERROR - telegram.ext.updater - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2021-05-06 19:12:45,704 - ERROR - root - urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) - Class: TelegramBot - None
2021-05-06 19:13:03,548 - ERROR - telegram.ext.updater - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2021-05-06 19:13:03,549 - ERROR - root - urllib3 HTTPError ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')) - Class: TelegramBot - None
2021-05-06 19:13:48,103 - WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x1136bef10>, 'Connection to api.telegram.org timed out. (connect timeout=10)')': /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates
2021-05-06 19:14:02,073 - WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x106448ad0>, 'Connect timed out. (connect timeout=10)')': /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates
2021-05-06 19:14:15,487 - WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x106448ad0>, 'Connect timed out. (connect timeout=10)')': /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates
2021-05-06 19:14:30,215 - ERROR - telegram.ext.updater - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x106448ad0>, 'Connect timed out. (connect timeout=10)'))
2021-05-06 19:14:30,216 - ERROR - root - urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x106448ad0>, 'Connect timed out. (connect timeout=10)')) - Class: TelegramBot - None
2021-05-06 19:14:45,490 - WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x106448ad0>, 'Connect timed out. (connect timeout=10)')': /bot1836642794:AAFZGQTSM4Z4zoNUoqf5uYXhofjg0V9i9bI/getUpdates
